version: '3.1'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./script.sql:/script.sql
      - ./exercices/:/exercices
      - data:/var/lib/postgresql/data

volumes:
  data:
